remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-remote-theme 
  - jekyll-relative-links
title: Branden's Bonfire
description: Come on over and take a seat. Let's chat. 
relative_links:
  enabled: true
  collections: true
include:
  - ABOUT.md
